//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lm.Eic.App.Mes.Window.Common
{
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lm.Eic.App.Mes.Window.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 Select objects to add 的本地化字符串。
        /// </summary>
        internal static string AddRemoveDetailEntities_SelectObjects
        {
            get
            {
                return ResourceManager.GetString("AddRemoveDetailEntities_SelectObjects", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Confirmation 的本地化字符串。
        /// </summary>
        internal static string Confirmation_Caption
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Caption", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Do you want to delete this {0}? 的本地化字符串。
        /// </summary>
        internal static string Confirmation_Delete
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Click OK to reload the entity and lose unsaved changes. Click Cancel to continue editing data. 的本地化字符串。
        /// </summary>
        internal static string Confirmation_Reset
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Reset", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Are you sure you want to reset layout? Reopen this view for the new layout to take effect. 的本地化字符串。
        /// </summary>
        internal static string Confirmation_ResetLayout
        {
            get
            {
                return ResourceManager.GetString("Confirmation_ResetLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Do you want to save changes? 的本地化字符串。
        /// </summary>
        internal static string Confirmation_Save
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You need to save the parent {0} entity before adding a new record. Do you want to save it now? 的本地化字符串。
        /// </summary>
        internal static string Confirmation_SaveParent
        {
            get
            {
                return ResourceManager.GetString("Confirmation_SaveParent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似  * 的本地化字符串。
        /// </summary>
        internal static string Entity_Changed
        {
            get
            {
                return ResourceManager.GetString("Entity_Changed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似  (Deleted) 的本地化字符串。
        /// </summary>
        internal static string Entity_Deleted
        {
            get
            {
                return ResourceManager.GetString("Entity_Deleted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似  (New) 的本地化字符串。
        /// </summary>
        internal static string Entity_New
        {
            get
            {
                return ResourceManager.GetString("Entity_New", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 DataService Request Error 的本地化字符串。
        /// </summary>
        internal static string Exception_DataServiceRequestErrorCaption
        {
            get
            {
                return ResourceManager.GetString("Exception_DataServiceRequestErrorCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Update Error 的本地化字符串。
        /// </summary>
        internal static string Exception_UpdateErrorCaption
        {
            get
            {
                return ResourceManager.GetString("Exception_UpdateErrorCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Validation Error 的本地化字符串。
        /// </summary>
        internal static string Exception_ValidationErrorCaption
        {
            get
            {
                return ResourceManager.GetString("Exception_ValidationErrorCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning_Caption
        {
            get
            {
                return ResourceManager.GetString("Warning_Caption", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Some fields contain invalid data. Click OK to close the page and lose unsaved changes. Press Cancel to continue editing data. 的本地化字符串。
        /// </summary>
        internal static string Warning_SomeFieldsContainInvalidData
        {
            get
            {
                return ResourceManager.GetString("Warning_SomeFieldsContainInvalidData", resourceCulture);
            }
        }
    }
}
